apiVersion: v1
kind: Service
metadata:
  name: bankapp-blue-service
  namespace: webapps
spec:
  selector:
    app: bankapp
    version: blue
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-green-service
  namespace: webapps
spec:
  selector:
    app: bankapp
    version: green
  ports:
    - port: 8080
      targetPort: 8080
